version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      python-test-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
